name: Update Service Worker Cache Version

on:
  push:
    branches:
      - main

jobs:
  update-cache-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set cache version to current date
        run: |
          DATE=$(date +"%d%b%Y" | tr '[:upper:]' '[:lower:]')
          sed -i "s/^const cacheVersion = .*/const cacheVersion = '${DATE}';/" sw.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add sw.js
          git commit -m "chore: update service worker cacheVersion to ${DATE}" || exit 0
          git push
